const tiposIntegracoes = [
	"local",
	"empresa",
	"categoria",
	"categoriaparceiro",
	"cliente",
	"atributo",
	"atributovalor",
	"estoque",
	"preco",
	"marca",
	"departamento",
	"produto",
	"produtoempresa",
	"anuncio",
	"vendedor",
	"pedido",
	"cliente",
	"transportadora",
	"pedido_faturado",
	"pedido_faturado_canal",
	"pedido_enviado",
	"pedido_concluido",
	"pedido_cancelado",
	"variacao",
	"imagens_produtos_ftp",
]

module.exports = { tiposIntegracoes }
